

// Generated by slyft.io
// This code part has been generated on an "as is" basis, without warranties or conditions of any kind.

// slyftlet=c99-generic-msgpack

#ifndef tutci_BOUNDS_H
#define tutci_BOUNDS_H

#include "mpack/mpack.h"

struct TUTCI__bounds {
  /* lower bound value */
  int32_t	lowerbound;
  /* upper bound value */
  int32_t	upperbound;

  /**
  * Wipes contents to \0
  * @param self      pointer to target struct TUTCI__bounds
  */
  void (*TUTCI__bounds_clean)(struct TUTCI__bounds *self);

  /**
  * Given an input buffer and its size, this functions parses the elements
  * of struct TUTCI__bounds
  * @param self          pointer to target struct TUTCI__bounds
  * @param input_buf     input buffer
  * @param sz_input_buf  size of input buffer
  * @return 0=success, 1=error
  */
  int (*TUTCI__bounds_parse)(struct TUTCI__bounds *self, const uint8_t *input_buf, size_t sz_input_buf);

  /**
  * Given a msgpack reader, this functions parses the elements
  * of struct TUTCI__bounds
  * @param self          pointer to target struct TUTCI__bounds
  * @param reader        pointer to mpack reader struct
  */
  void (*TUTCI__bounds_parse_mpack)(struct TUTCI__bounds *self, mpack_reader_t *reader);

  /**
  * Given a struct TUTCI__bounds, this function serializes it into given output buffer.
  * @param self              pointer to source struct TUTCI__bounds
  * @param output_buf        output buffer
  * @param sz_output_buf     size of output buffer
  * @return Length of output buf (0=error)
  */
  size_t (*TUTCI__bounds_serialize)(const struct TUTCI__bounds *self, uint8_t *output_buf, size_t sz_output_buf);

  /**
  * Given a struct TUTCI__bounds, this function serializes it into given mpack writer.
  * @param self              pointer to source struct TUTCI__bounds
  * @param writer 	         pointer to mpack writer struct
  */
  void (*TUTCI__bounds_serialize_mpack)(const struct TUTCI__bounds *self, mpack_writer_t *writer);

};

/**
 * Initializes struct struct TUTCI__bounds. empties fields, sets function pointers
 * @param self  struct TUTCI__bounds
 */
void TUTCI__bounds_init(struct TUTCI__bounds *self);


/* ORIGINAL SCHEMA
{"$schema"=>"http://json-schema.org/draft-04/schema#", "id"=>"bounds", "title"=>"Boundary Values", "description"=>"Specify boundary values", "type"=>"object", "properties"=>{"lowerbound"=>{"type"=>"integer", "description"=>"lower bound value"}, "upperbound"=>{"type"=>"integer", "description"=>"upper bound value"}}, "additionalProperties"=>false, "required"=>["lowerbound", "upperbound"], "minProperties"=>2}
 */
#endif		//tutci_BOUNDS_H

