
// Generated by slyft.io
// This code part has been generated on an "as is" basis, without warranties or conditions of any kind.

// application-part header



    #include "Arduino.h"

#include "microcoap/coap.h"

// include data structure headers
#include "poti.h"
#include "led.h"
#include "bounds.h"

// struct TUTCI__bounds
#include "bounds.h"
// struct TUTCI__led
#include "led.h"
// struct TUTCI__poti
#include "poti.h"



//
// CoAP Application level handlers
//

// -- GET  /bounds

struct TUTCI__coapled__get___bounds_req {
    struct {

    } data;
};

struct TUTCI__coapled__get___bounds_resp {
    coap_responsecode_t  response_code;
    struct {


        // data struct for response code 205
        struct TUTCI__bounds  bounds_205;

    } data;
};

// -- Application level handler for GET to /bounds
bool TUTCI__coapled__get___bounds(
    struct TUTCI__coapled__get___bounds_req *req,
    struct TUTCI__coapled__get___bounds_resp *resp);


// -- POST  /bounds

struct TUTCI__coapled__post___bounds_req {
    struct {

        struct TUTCI__bounds  bounds;

    } data;
};

struct TUTCI__coapled__post___bounds_resp {
    coap_responsecode_t  response_code;
    struct {

    } data;
};

// -- Application level handler for POST to /bounds
bool TUTCI__coapled__post___bounds(
    struct TUTCI__coapled__post___bounds_req *req,
    struct TUTCI__coapled__post___bounds_resp *resp);


// -- GET  /led

struct TUTCI__coapled__get___led_req {
    struct {

    } data;
};

struct TUTCI__coapled__get___led_resp {
    coap_responsecode_t  response_code;
    struct {


        // data struct for response code 205
        struct TUTCI__led  led_205;

    } data;
};

// -- Application level handler for GET to /led
bool TUTCI__coapled__get___led(
    struct TUTCI__coapled__get___led_req *req,
    struct TUTCI__coapled__get___led_resp *resp);


// -- GET  /poti

struct TUTCI__coapled__get___poti_req {
    struct {

    } data;
};

struct TUTCI__coapled__get___poti_resp {
    coap_responsecode_t  response_code;
    struct {


        // data struct for response code 205
        struct TUTCI__poti  poti_205;

    } data;
};

// -- Application level handler for GET to /poti
bool TUTCI__coapled__get___poti(
    struct TUTCI__coapled__get___poti_req *req,
    struct TUTCI__coapled__get___poti_resp *resp);
