
// Generated by slyft.io
// This code part has been generated on an "as is" basis, without warranties or conditions of any kind.

// application-part


#include "Arduino.h"

#include "microcoap/coap.h"
#include "coapled_app.h"

// include data structure headers
#include "poti.h"
#include "led.h"
#include "bounds.h"
#include "ledapp.h"
#include "ledpoti.h"


ledpoti_s c_obj;
//
// CoAP Application level handlers
//

// -- Application level handler for GET to /bounds
bool TUTCI__coapled__get___bounds(
    struct TUTCI__coapled__get___bounds_req *req,
    struct TUTCI__coapled__get___bounds_resp *resp) {

    resp->data.bounds_205.lowerbound = ledpoti_get_lower_bound(&c_obj);
    resp->data.bounds_205.upperbound = ledpoti_get_upper_bound(&c_obj);
    resp->response_code = COAP_RSPCODE_CONTENT;

    Serial.print("TUTCI__coapled__get___lower_bound = ");
    Serial.println(ledpoti_get_lower_bound(&c_obj));
    Serial.print("TUTCI__coapled__get___upper_bound = ");
    Serial.println(ledpoti_get_upper_bound(&c_obj));

    return true;
}


// -- Application level handler for POST to /bounds
bool TUTCI__coapled__post___bounds(
    struct TUTCI__coapled__post___bounds_req *req,
    struct TUTCI__coapled__post___bounds_resp *resp) {

    ledpoti_set_bounds(&c_obj, req->data.bounds.lowerbound, req->data.bounds.upperbound);
    resp->response_code = COAP_RSPCODE_CHANGED;

    return true;
}


// -- Application level handler for GET to /led
bool TUTCI__coapled__get___led(
    struct TUTCI__coapled__get___led_req *req,
    struct TUTCI__coapled__get___led_resp *resp) {

    resp->data.led_205.ledstate = ledapp_get_led_value();
    resp->response_code = COAP_RSPCODE_CONTENT;

    Serial.print("TUTCI__coapled__get___poti = ");
    Serial.println(resp->data.led_205.ledstate);

    return true;
}


// -- Application level handler for GET to /poti
bool TUTCI__coapled__get___poti(
    struct TUTCI__coapled__get___poti_req *req,
    struct TUTCI__coapled__get___poti_resp *resp) {

    resp->data.poti_205.potval = ledapp_get_poti_value();
    resp->response_code = COAP_RSPCODE_CONTENT;

    Serial.print("TUTCI__coapled__get___poti = ");
    Serial.println(resp->data.poti_205.potval);

    return true;
}
