

// Generated by slyft.io
// This code part has been generated on an "as is" basis, without warranties or conditions of any kind.

// slyftlet=c99-generic-msgpack

#ifndef tutci_LED_H
#define tutci_LED_H

#include "mpack/mpack.h"

struct TUTCI__led {
  /* true->1, false->0 */
  int32_t	ledstate;

  /**
  * Wipes contents to \0
  * @param self      pointer to target struct TUTCI__led
  */
  void (*TUTCI__led_clean)(struct TUTCI__led *self);

  /**
  * Given an input buffer and its size, this functions parses the elements
  * of struct TUTCI__led
  * @param self          pointer to target struct TUTCI__led
  * @param input_buf     input buffer
  * @param sz_input_buf  size of input buffer
  * @return 0=success, 1=error
  */
  int (*TUTCI__led_parse)(struct TUTCI__led *self, const uint8_t *input_buf, size_t sz_input_buf);

  /**
  * Given a msgpack reader, this functions parses the elements
  * of struct TUTCI__led
  * @param self          pointer to target struct TUTCI__led
  * @param reader        pointer to mpack reader struct
  */
  void (*TUTCI__led_parse_mpack)(struct TUTCI__led *self, mpack_reader_t *reader);

  /**
  * Given a struct TUTCI__led, this function serializes it into given output buffer.
  * @param self              pointer to source struct TUTCI__led
  * @param output_buf        output buffer
  * @param sz_output_buf     size of output buffer
  * @return Length of output buf (0=error)
  */
  size_t (*TUTCI__led_serialize)(const struct TUTCI__led *self, uint8_t *output_buf, size_t sz_output_buf);

  /**
  * Given a struct TUTCI__led, this function serializes it into given mpack writer.
  * @param self              pointer to source struct TUTCI__led
  * @param writer 	         pointer to mpack writer struct
  */
  void (*TUTCI__led_serialize_mpack)(const struct TUTCI__led *self, mpack_writer_t *writer);

};

/**
 * Initializes struct struct TUTCI__led. empties fields, sets function pointers
 * @param self  struct TUTCI__led
 */
void TUTCI__led_init(struct TUTCI__led *self);


/* ORIGINAL SCHEMA
{"$schema"=>"http://json-schema.org/draft-04/schema#", "id"=>"led", "title"=>"LED State", "description"=>"LED State", "type"=>"object", "properties"=>{"ledstate"=>{"type"=>"integer", "description"=>"true->1, false->0"}}, "additionalProperties"=>false, "required"=>["ledstate"], "minProperties"=>1}
 */
#endif		//tutci_LED_H

